image: alpine

stages:
  - schedule

before_script:
  - apk -U add git

update-repo:
  stage: schedule
  script:
    - git clone --no-checkout "git://git.moodle.org/moodle.git" vendormoodle
    - cd vendormoodle
    - git remote add gripsmoodle "https://oauth2:$ACCESS_TOKEN@gitlab.ur.de/e-learning/moodle.git"
    - git push gripsmoodle --tags "refs/remotes/origin/*:refs/heads/*"
  tags: 
    - rrzwdk1