image: alpine

stages:
  - schedule

before_script:
  - apk -U add git

update-repo:
  stage: schedule
  script:
    - git clone --no-checkout "git://git.moodle.org/moodle.git" vendormoodle
    - cd vendormoodle
    - rm .git/refs/remotes/origin/HEAD
    - git remote add gripsmoodle "https://oauth2:$ACCESS_TOKEN@gitlab.uni-regensburg.de/e-learning/moodle.git"
    - git push -u -f --tags gripsmoodle "+refs/remotes/origin/*:refs/heads/*"
  tags: 
    - rrzwdk1